export const skills = [
  'JavaScript',
  'TypeScript',
  'React',
  'Redux',
  'Ruby',
  'Ruby on Rails',
  'Linux',
  'Problem Solving',
  'Project management',
  'Communication',
  'Git',
  'Attention to detail',
  'SQL',
  'Teamwork',
  'Leadership',
  'Time management',
  'Self-motivation',
  'Conflict resolution',
  'Critical thinking',
  'Firebase',
  'Mentoring',
  'Python',
  'Node.js',
  'Full-stack development',
  'Responsive web design',
];
